name: Python CI actions

on: [pull_request]
env:
  PGDATABASE: harvester_pipeline_test
  PGPASSWORD: postgres
  PGUSER: postgres
  PGHOST: localhost
  PGPORT: 5432

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.4
        env:
          POSTGRES_DB: harvester_pipeline_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -U -r requirements.txt
        pip install -U -r dev-requirements.txt
#        git submodule update --init --recursive
#        pip install -U -r harvester_gRPC/requirements.txt
    - name: Test with pytest
      run: |
        py.test test/harvester

    - uses: actions/upload-artifact@v2
      with:
        name: coverage-harvesterpipeline
        path: .coverage


  # coveralls:

  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8

  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade wheel setuptools pip
  #       pip install coverage==5.2.1
  #       pip install coveralls==2.2.0
  #   - uses: actions/download-artifact@master
  #     with:
  #       name: coverage-harvesterpipeline

  #   - name: Coveralls
  #     run: coveralls
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

